; ==============================================================================
; Plataforma y Entorno de Compilación: Estación SIA - Pantalla CYD (3.5" ST7796)
; Placa: Hosyond ESP32-3248S035R (Cheap Yellow Display 3.5")
; Resolución: 480x320 px en orientación horizontal
; ==============================================================================

[platformio]
default_envs = esp32-3248S035R

[env:esp32-3248S035R]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    paulstoffregen/XPT2046_Touchscreen@0.0.0-alpha+sha.26b691b2c8
    ricmoo/QRCode@^0.0.1

build_flags =
    -std=gnu++17
    ; Desactivar carga de User_Setup.h global de TFT_eSPI
    -DUSER_SETUP_LOADED=1
    
    ; Driver ST7796 para CYD 3.5"
    -DST7796_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    
    ; Pines del bus SPI del Display
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=27
    -DTFT_BACKLIGHT_ON=1
    
    ; Fuentes embebidas activas en TFT_eSPI
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    
    ; Frecuencia SPI del bus (40 MHz para renderizado óptimo y estable)
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000
