[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 460800
upload_port = COM7

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    miguelbalboa/MFRC522 @ ^1.4.11

build_flags =
    -DCORE_DEBUG_LEVEL=3
